/*
 * BuildInfo.h - per-build constants (HASHES, SYSCALL #, EXPECTED SHIM IMAGES)
 *
 * AUTO-GENERATED by scripts/resolve_syscall.py at build time. Hand edits
 * here may be overwritten. To update for a new Windows build:
 *
 *   py scripts/resolve_syscall.py C:\Windows\System32\ntdll.dll NtCreateProfile
 *
 * The script computes ntdll.dll SHA-256, extracts NtCreateProfile's syscall
 * number from the Zw prologue (mov eax, IMM32), and emits a struct entry.
 *
 * Note: hash tracks ntdll.dll because that file embeds syscall numbers in
 * its export thunks. ntoskrnl.exe also versions in lockstep with ntdll on
 * any given Windows build, so ntdll hash is a sufficient build identifier.
 */
#pragma once

#include <stdint.h>

#define OPHION_VERSION_MAJOR  0
#define OPHION_VERSION_MINOR  1
#define OPHION_VERSION_PATCH  0
#define OPHION_VERSION_U32    ((OPHION_VERSION_MAJOR << 16) | (OPHION_VERSION_MINOR << 8) | OPHION_VERSION_PATCH)

// Per-Windows-build table. First 8 bytes of ntdll.dll SHA-256 + syscall #
// for NtCreateProfile. Update via scripts/resolve_syscall.py.
typedef struct {
    uint8_t  sha256_first8[8];
    uint16_t nt_create_profile_syscall_num;
    char     build_label[48];
} ntos_build_t;

static const ntos_build_t kNtosBuilds[] = {
    // Resolved 2026-05-18 from this dev rig (ReviOS 10 19045) ntdll.dll
    { {0x36,0xB1,0xA6,0x2E,0x4B,0xF6,0xBF,0x7D}, 0x00BB,
      "Win10 19045 (ntdll TS=7EC9C15D)" },
};

#define K_NTOS_BUILDS_COUNT  (sizeof(kNtosBuilds)/sizeof(kNtosBuilds[0]))

// Expected SHA-256 of authorized cheat exe (.text section). Used by VMM during
// OPHION_OP_REGISTER to reject untrusted callers. AUTO-GENERATED at cheat exe
// build time; embedded into MongilLoader so the loader is the trust anchor.
static const uint8_t kExpectedCheatExeHash[32] = {
    0xE4, 0x18, 0x55, 0xE9, 0x2A, 0x46, 0xF8, 0x0C, 0xAF, 0xFC, 0x51, 0x2F, 0x1A, 0xD7, 0xB1, 0x54, 0x56, 0x94, 0xD9, 0xC2, 0xD1, 0x3D, 0xBE, 0x1F, 0x45, 0xD2, 0x44, 0xBF, 0xA7, 0xC1, 0x7C, 0x4E
};

// Build-epoch salt used in any hash combining (mirrors vgk's salt-sandwich
// pattern but with our own constant). Rotate per major release.
#define K_OPHION_BUILD_SALT  "OPHION-2026-05-SALT-v1"

// Common syscall numbers on this Win10 19045 build (resolved via ntdll Zw thunks):
#define WIN10_19045_NtCreateProfile         0x00BB
#define WIN10_19045_NtAllocateVirtualMemory 0x0018
#define WIN10_19045_NtClose                 0x000F
#define WIN10_19045_NtCreateFile            0x0055
